---
- hosts: all
  tasks:
    - name: Update apt
      apt: update_cache=yes
      sudo: yes

    - name: Install base packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - git
        - build-essential
        - nodejs
        - npm

    - name: install n (node version installer/switcher)
      npm: name=n state=present global=yes
 
    - name: install the latest stable version of node
      shell: n stable
 
    - name: Create web user
      user: name=web
 
    - name: Create project folder
      file: path=/var/www group=web owner=web mode=755 state=directory
